name = "homework-helper"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "homework-helper"
database_id = "e78c453b-14e8-4644-ad2f-79f786a35543"
